### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by iHunter69** [worse-666/csgo_external_ahk_hack#11]
how to run this, can u make detailed vid on youtube

**Comment by worse-666** [comment]
1. Install autohotkey unicode 64 bit.
2. Run csgo external hack.ahk

**Comment by iHunter69** [comment]
> 1. Install autohotkey unicode 64 bit.
> 2. Run csgo external hack.ahk

still doesnt work shows an error

**Comment by iHunter69** [comment]
> 1. Install autohotkey unicode 64 bit.
> 2. Run csgo external hack.ahk

my bad older vversion works
