### ISSUE TITLE
1.1.4 working instead of 1.2.2

### ISSUE THREAD

**Issue by iHunter69** [worse-666/csgo_external_ahk_hack#13]
now the creator of this is pretty nice guy but the problem with the scripts is that 1.1.4 working but is limited, whenever i open 1.2.2 it says line 2 is an error, 1.1.4 is working fine very excellent, but limited by certain crashes, when u open the main menu while its injected or press TAB it frequently crashes the game. overall 10/10 even if it is limited

**Comment by worse-666** [comment]
I'm sorry I forgot to upload a new file, it should work now

**Comment by iHunter69** [comment]
> I'm sorry I forgot to upload a new file, it should work now

thank you
