### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by ToJaRedi** [worse-666/csgo_external_ahk_hack#38]
Any idea why this doesn't work?

SetConVar(client, cl_grenadepreview, enable_grenade_prediction ? 1:0, "Int")

SetConVar(ByRef base, ByRef offset, value, type:="Float") {
	VarSetCapacity(v, 4)
	NumPut(value, v, 0, type="Float" ? "Float":"Int")
	thisPtr := base + offset - (type="Float" ? 0x2C:0x30)
	,xored := NumGet(v, 0, "Int") ^ thisPtr
	csgo.write(base + offset, xored, "Uint")
}

**Comment by worse-666** [comment]
Because I didn't update the cvar offset

**Comment by ToJaRedi** [comment]
> Because I didn't update the cvar offset

Could you please update it?

**Comment by worse-666** [comment]
Sorry I'm not motivated to update this project because AHK is not suitable for programming hacks and some reasons.
I can tell you how to do it.
Download [ConvarManager](https://github.com/worse-666/ahk_autostrafer/blob/main/lib/ConvarManager.ahk) and add these to csgo external hack.ahk .

#Include ConvarManager.ahk

Cvar := new ConvarManager()

cl_grenadepreview:= Cvar.FindFast("cl_grenadepreview")

;put this in the loop
cl_grenadepreview.SetInt(enable_grenade_prediction ? 1:0)

**Comment by ToJaRedi** [comment]
> Sorry I'm not motivated to update this project because AHK is not suitable for programming hacks and some reasons. I can tell you how to do it. Download [ConvarManager](https://github.com/worse-666/ahk_autostrafer/blob/main/lib/ConvarManager.ahk) and add these to csgo external hack.ahk .
> 
> #Include ConvarManager.ahk
> 
> Cvar := new ConvarManager()
> 
> cl_grenadepreview:= Cvar.FindFast("cl_grenadepreview")
> 
> ;put this in the loop cl_grenadepreview.SetInt(enable_grenade_prediction ? 1:0)
> 
> ;You can modify all cvars this way, but some [cvars](https://www.unknowncheats.me/forum/counterstrike-global-offensive/173295-convars-checked-valve-servers.html) are checked by the valve.

Okay, Thanks

**Comment by ToJaRedi** [comment]
> Sorry I'm not motivated to update this project because AHK is not suitable for programming hacks and some reasons. I can tell you how to do it. Download [ConvarManager](https://github.com/worse-666/ahk_autostrafer/blob/main/lib/ConvarManager.ahk) and add these to csgo external hack.ahk .
> 
> #Include ConvarManager.ahk
> 
> Cvar := new ConvarManager()
> 
> cl_grenadepreview:= Cvar.FindFast("cl_grenadepreview")
> 
> ;put this in the loop cl_grenadepreview.SetInt(enable_grenade_prediction ? 1:0)
> 
> ;You can modify all cvars this way, but some [cvars](https://www.unknowncheats.me/forum/counterstrike-global-offensive/173295-convars-checked-valve-servers.html) are checked by the valve.

I have a little problem ... imgui doesn't show up
