### ISSUE TITLE
IMGUI problem

### ISSUE THREAD

**Issue by ToJaRedi** [worse-666/csgo_external_ahk_hack#39]
Hello, so I added what I need to cheat but it doesn't show gui... Can you send me a sample source code that works properly with ConvarManager please?  [Source code here with ConVar added](https://pastebin.com/raw/Ns2csLmr)

**Comment by worse-666** [comment]
I think the offset is wrong so stuck in [this](https://github.com/worse-666/ahk_autostrafer/blob/main/lib/ConvarManager.ahk#L8) loop.
Make sure the [offset](https://github.com/frk1/hazedumper) is the latest version.

**Comment by ToJaRedi** [comment]
> I think the offset is wrong so stuck in [this](https://github.com/worse-666/ahk_autostrafer/blob/main/lib/ConvarManager.ahk#L8) loop. Make sure the [offset](https://github.com/frk1/hazedumper) is the latest version.

Offsets are good. I looked through everything again and found the problem :) Everything is working fine, thanks for your help
